### ISSUE TITLE
Use URI-escaping when creating IDs

### ISSUE THREAD

**Issue by wafschneider** [lcnetdev/marc2bibframe2#46]
From the README:

>*Note* - there is no built-in facility in the stylesheets for URI-encoding (of the ID field)

It would be good to correct this. It came up when @wattsferry was converting records with space characters in the 001.

Perhaps we should also remove leading and trailing spaces from the 001 value.

**Comment by wafschneider** [comment]
This update has been installed on mprxyvls02.loc.gov for recordSchema bibframe2-dev, but of course LC records have the record id as an integer in the 001, so you see no change. The updated unit test for record ID demonstrates the url-encoding.

**Comment by wattsferry** [comment]
Thanks Wayne! Cheers, Clay  



On August 4, 2017 at 5:44:22 PM EDT, Wayne Schneider <notifications@github.com> wrote:This update has been installed on mprxyvls02.loc.gov for recordSchema bibframe2-dev, but of course LC records have the record id as an integer in the 001, so you see no change. The updated unit test for record ID demonstrates the url-encoding.  —You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.           {"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/lcnetdev/marc2bibframe2","title":"lcnetdev/marc2bibframe2","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/lcnetdev/marc2bibframe2"}},"updates":{"snippets":[{"icon":"PERSON","message":"@wafschneider in #46: This update has been installed on mprxyvls02.loc.gov for recordSchema bibframe2-dev, but of course LC records have the record id as an integer in the 001, so you see no change. The updated unit test for record ID demonstrates the url-encoding."}],"action":{"name":"View Issue","url":"https://github.com/lcnetdev/marc2bibframe2/issues/46#issuecomment-320359924"}}}
