### ISSUE TITLE
Convert ISBN-10 to ISBN-13?

### ISSUE THREAD

**Issue by osma** [lcnetdev/marc2bibframe2#6]
I noticed that marc2bibframe2 doesn't attempt to convert ISBN-10 codes to corresponding ISBN-13 (i.e. add `978` prefix and recalculate the check digit). The old `marc2bibframe` converter did this.

Do you plan to add such a feature or is this out of scope for `marc2bibframe2`?

**Comment by osma** [comment]
Also, the old `marc2bibframe` converter stripped dashes from ISBNs, leaving only numbers. I'm not sure whether that's the desirable thing to do, just noting that the new converter behaves differently as it leaves the dashes intact.

**Comment by kirkhess** [comment]
On the second comment, it seems to me that we should take the number from marc, remove the dashes and store it as a bf:value, but leave the dashed version as a bf:label. We'll think about that one.

On the first comment we thought that we didn't need to do this anymore since those are display issues - we might need to issue guidance on doing this on display rather than adding it to the ontology/converter. Do you think we should bring those two back?

**Comment by osma** [comment]
I think it's fine to consider the ISBN-10 to ISBN-13 conversion out of scope, as long as it's a deliberate decision. As you said it's more of a display issue.

**Comment by wafschneider** [comment]
LoC will look at specifying processing for different identifiers based on pilot results

**Comment by jodiw01** [comment]
won't fix at this time, but it could be reconsidered in the future
